// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvcRXp5IZpXCHQQ6Q83jFp6xfe5dAs68',
    appId: '1:859875644360:web:a96c026b3e0c52dfa3e6fd',
    messagingSenderId: '859875644360',
    projectId: 'drive-pool-80c92',
    authDomain: 'drive-pool-80c92.firebaseapp.com',
    storageBucket: 'drive-pool-80c92.appspot.com',
    measurementId: 'G-SQ8V4R2PEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uCRQO5DoZ_cXpQdpcwvrOag3V6jGr58',
    appId: '1:859875644360:android:a36a9326dc53342ba3e6fd',
    messagingSenderId: '859875644360',
    projectId: 'drive-pool-80c92',
    storageBucket: 'drive-pool-80c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB77WWNhT6ucG38dHKECb4URXy3QelJ6pI',
    appId: '1:859875644360:ios:7285dca6052e018ba3e6fd',
    messagingSenderId: '859875644360',
    projectId: 'drive-pool-80c92',
    storageBucket: 'drive-pool-80c92.appspot.com',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB77WWNhT6ucG38dHKECb4URXy3QelJ6pI',
    appId: '1:859875644360:ios:7285dca6052e018ba3e6fd',
    messagingSenderId: '859875644360',
    projectId: 'drive-pool-80c92',
    storageBucket: 'drive-pool-80c92.appspot.com',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyvcRXp5IZpXCHQQ6Q83jFp6xfe5dAs68',
    appId: '1:859875644360:web:31d8c740e13746d3a3e6fd',
    messagingSenderId: '859875644360',
    projectId: 'drive-pool-80c92',
    authDomain: 'drive-pool-80c92.firebaseapp.com',
    storageBucket: 'drive-pool-80c92.appspot.com',
    measurementId: 'G-1DX114CGCL',
  );
}
